# Generated by Django 5.0.7 on 2024-09-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('retype_password', models.CharField(max_length=50)),
                ('laptop', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('about', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
                ('Checkbox', models.CharField(max_length=50)),
                ('files', models.CharField(max_length=50)),
                ('ram', models.IntegerField()),
                ('ssd', models.CharField(max_length=50)),
                ('youtube_channal', models.BooleanField(max_length=50)),
            ],
        ),
    ]
